#!/bin/bash
source /etc/profile
time=`date +%Y%m%d%H%M%S`
ps -ef | grep -v grep | grep agent.py| awk '{print $2}'|xargs kill -9>/dev/null 2>&1
ps -ef | grep udp
if (ls /home/opvis/Agent*.tar.gz ) >/dev/null 2>&1;then
echo "文件存在"
rm -rf /home/opvis/Agent/*
mv /home/opvis/Agent*.tar.gz /home/opvis/Agent.tar.gz
tar xzvf /home/opvis/Agent.tar.gz -C /home/opvis/
mv /home/opvis/Agent.tar.gz /home/opvis/Agent.tar.gz$time
else
echo "文件不存在"
fi
cd /home/opvis/Agent
./start.sh
ps -ef | grep agent.py